insert into produto (codigo, nomeproduto, unidade, preco)  values (	451	,'Abacate  	','kg',9.80	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	1865	,'Abacaxi 	','un ',11.20	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	5450	,'Abobora Barbara 	','kg',4.90	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	5642	,'Abóbora Bola Amarela	','kg',3.92	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	5642	,'Abóbora Bola verde	','kg',3.92	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	5642	,'Abóbora Bola Verde Clara	','kg',3.92	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	2448	,'Abobora Cabutia/Japonesa  	','Kg',4.20	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	5485	,'Abobora Caipira 	','kg',3.49	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	2446	,'Abobora Italia 	','500g',4.00	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	3072	,'Abóbora Italia granel	','Kg',4.48	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	3072	,'Abobora Italia restaurante	','kg',4.48	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	5634	,'Abóbora Japonesa Processada	','500g',5.60	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	2449	,'Abobora Madura	','kg',3.50	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	2449	,'Abobora Madura restaurante	','kg',3.50	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	2447	,'Abobora Menina 	','500g',4.00	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	3073	,'Abobora Menina (granel)	','kg',14.00	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	4759	,'Abóbora mini moranga	','kg',14.00	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	5486	,'Abobora Moranga	','Kg',4.20	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	1205	,'Açafrao (granel) TF	','kg',31.68	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	5223	,'Açafrao 100g	','100g',4.20	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	5646	,'Açafrão em pó 	','30g',9.44	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	5647	,'Açafrão em pó 	','50g',15.20	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	2450	,'Acelga	','un',3.50	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	5433	,'Acerola 500g	','500g',4.51	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	3130	,'Acerola congelada - P	','500g',0.00	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	2451	,'Agriao da água 300g	','300g',4.20	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	2452	,'Agriao da terra 300g	','300g',3.50	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	5423	,'Alecrim 70g	','70g',2.10	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	5679	,'Alecrim desidratada 	','20g',4.00	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	2453	,'Alface Americana	','un',2.90	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	5487	,'Alface baby Americana / Frizee Roxa	','bj',3.36	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	5488	,'Alface baby Americana / Frizee Verde	','bj',3.36	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	5489	,'Alface baby Frizee Roxa e Verde	','bj',3.36	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	5490	,'Alface Baby Mix	','bdj',3.36	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	5601	,'Alface Baby Mix americana e roxa	','bdj',3.36	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	2454	,'Alface Crespa	','un',2.45	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	5491	,'Alface Crespa Crocantela	','un ',2.45	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	2455	,'Alface Frisee	','un ',2.45	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	2456	,'Alface Lisa	','un ',2.45	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	2457	,'Alface Mimosa	','un ',2.45	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	5451	,'Alface Mimosa Roxa	','un ',2.45	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	2458	,'Alface Romana	','un ',2.45	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	5452	,'Alface Romana Crocante	','un ',2.45	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	5492	,'Alface Romanela	','un ',2.45	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	2459	,'Alface Roxa	','un ',2.45	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	5581	,'Alface rubinela roxa	','un ',2.45	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	5453	,'Alfavaca 70g	','70g',3.36	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	5649	,'Alho Cabeça Graudo	','200g',15.30	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	5651	,'Alho Cabeça Medio 	','200g',15.04	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	5653	,'Alho Cabeça Miudo	','200g',12.00	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	5650	,'Alho Debulhado Graudo 	','200g',15.30	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	5652	,'Alho Debulhado Médio 	','200g',15.30	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	5654	,'Alho Debulhado Miúdo 	','200g',12.00	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	5327	,'Alho descascado 150g	','150g',13.04	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	5315	,'Alho descascado 300g	','300g',24.15	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	1625	,'Alho Desidratado 20g	','20g',7.35	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	5595	,'Alho gourmet 150g	','150g',12.46	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	2460	,'Alho Porro 350g	','350g',4.20	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	5427	,'Alho-porro bulbo 250g	','250g',4.20	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	2461	,'Almeirao 300g	','300g',2.80	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	4556	,'Ameixa BDJ	','500g',7.00	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	4561	,'Ameixa granel	','kg',0.00	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	5493	,'Amora 75g	','75g',4.20	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	4340	,'Amora congelada 	','160g',8.70	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	5674	,'Arnica	','70g',03.08	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	5494	,'Atemoia 	','kg',10.78	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	5495	,'Avocado 500g	','500g',5.95	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	5496	,'Avocado kg	','kg',11.20	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	5449	,'Azedinha/vinagreira 100g	','100g',2.10	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	5616	,'Banana da Terra kg	','kg',4.76	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	5429	,'Banana Maça (granel)	','kg',6.16	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	5430	,'Banana Marmelo (granel)	','kg',4.76	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	5428	,'Banana Nanica (granel)	','kg',04.05	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	5434	,'Banana Ouro kg	','kg',4.69	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	5578	,'Banana praçã	','kg',4.76	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	4526	,'Banana Prata KG	','kg',5.32	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	5225	,'Batata Asterix 1 kg	','kg',9.10	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	5738	,'Batata Asterix 500g	','500G',5.53	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	5497	,'Batata Asterix Bolinha 1Kg	','1kg',8.25	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	2462	,'Batata Baroa 500g	','500g',10.50	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	2463	,'Batata Doce 500g	','500g',4.00	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	5411	,'Batata Doce Amarela 500G	','500g',3.50	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	5389	,'Batata Doce Branca 500g	','500g',3.50	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	5360	,'Batata Doce Granel	','kg',7.00	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	5374	,'Batata Doce Laranja 500g	','500g',3.50	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	5592	,'Batata Doce Roxa 500g	','500g',3.50	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	5498	,'Batata Inglesa (granel)	','kg ',7.00	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	3065	,'Batata Inglesa 1kg	','kg',7.70	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	4534	,'Batata Inglesa 500g	','500g',3.50	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	5262	,'Batata Inglesa Bolinha 1kg	','kg',6.00	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	5264	,'Batata Inglesa Bolinha 500g	','500G',3.50	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	2464	,'Batata Yakon 500g	','500g',4.20	);
insert into produto (codigo, nomeproduto, unidade, preco)  values ( null,'Batata Yakon Restaurante*	','kg',0.00	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	5436	,'Beldroega	','300g',2.10	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	3066	,'Berinjela (granel)	','kg',5.60	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	2465	,'Berinjela 500g	','500g',4.90	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	5500	,'Berinjela Japonesa 500g	','500g',3.50	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	5424	,'Bertalha	','Und',2.80	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	1653	,'Beterraba c/ Folha kg	','kg',5.60	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	3070	,'Beterraba granel	','kg',5.60	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	4742	,'Beterraba s/ Folha 500g	','500g',3.15	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	1653	,'Beterraba s/ Folha Kg	','kg',6.30	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	5475	,'Biriba 1kg	','1kg',5.74	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	5412	,'Boldo 70g	','70g',3.50	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	5576	,'Brocolis Japones 400g (und)	','400g',6.30	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	2468	,'Brocolis Japones kg	','kg',9.80	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	2467	,'Brocolis Ramoso / Comum	','400g',5.60	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	3981	,'Cafe moido 250g	','250g',15.20	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	3982	,'Cafe moido 500g	','500g',28.80	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	3983	,'Cafe Torrado Grao 250g	','250g',16.75	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	3984	,'Cafe Torrado Grao 500g	','500g',31.84	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	5502	,'Cagaita	','bdj',3.78	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	5437	,'Cajamanga 500G	','500g',4.20	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	671	,'Caju	','500g',8.40	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	5672	,'Cana Caiana sem Casca	','400g',3.70	);
insert into produto (codigo, nomeproduto, unidade, preco)  values ( null,'Capim cidreira	','70g',2.80	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	5457	,'Capim santo	','70g',2.80	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	5458	,'Capuchinha	','50g',5.60	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	5483	,'Caqui 	','Bdj',5.60	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	5602	,'Caqui RAMA FORTE	','Bdj',5.60	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	5625	,'Cara moela	','500g',7.00	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	5503	,'Carambola	','500g',3.50	);
insert into produto (codigo, nomeproduto, unidade, preco)  values ( null,'Carambola KG	','KG',7.00	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	5626	,'Carqueja 100g	','100g',3.92	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	3813	,'Cebola Comum Embalada 1kg	','kg',7.70	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	4750	,'Cebola Comum Embalada 500g	','500g',4.90	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	1997	,'Cebola Comum granel	','kg',7.00	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	5460	,'Cebola MÇ	','mç',7.00	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	5275	,'Cebola Roxa (granel)	','kg',8.00	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	5274	,'Cebola Roxa 1kg	','kg',8.40	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	4846	,'Cebola Roxa 500g	','500g',5.00	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	5461	,'Cebolete	','100g',2.10	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	2469	,'Cebolinha 100g	','100g',2.10	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	2445	,'Cebolinha Desidratada 	','10g',7.00	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	3040	,'Cebolinha/Alho desidratados	','20g',7.00	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	3071	,'Cenoura (granel)	','kg',5.60	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	2470	,'Cenoura c/folha	','1,200g',5.60	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	2470	,'Cenoura s/ Folha 1Kg	','kg',6.30	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	4477	,'Cenoura s/ Folha 500g	','500g',3.50	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	5076	,'Chalota 150g - seu menino	','150g',12.50	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	1628	,'Chalota Desidratada 20g - seu menino	','20g',7.00	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	5391	,'Chalota roseé round in natura 150g	','150g',12.46	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	5393	,'Chalota tailandesa 300g	','300g',23.40	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	2471	,'Cheiro Verde (coentro) 100g	','100g',2.10	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	5446	,'Cheiro Verde (salsa) 100g	','100g',2.10	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	5413	,'Chia 250g	','250g',6.72	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	5504	,'Chia kg	','Kg',15.40	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	2473	,'Chicoria	','un',2.10	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	4915	,'Chuchu (granel)	','kg',9.10	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	2474	,'Chuchu 500g	','500g',4.90	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	4755	,'Chuchu mini	','500g',5.20	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	5438	,'Coco Verde	','und',4.20	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	2040	,'Coentro 100g	','100g',2.10	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	5226	,'Cogumelo  funghi desidratado 100g	','100g',35.00	);
insert into produto (codigo, nomeproduto, unidade, preco)  values ( null,'Cogumelo Champignon em conserva 	','100g',0.00	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	547	,'Cogumelo Champignon in natura 200G	','200g',11.20	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	5464	,'Cogumelo shimeji Branco 200g	','200g',11.20	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	535	,'Cogumelo Shimeji Branco Desidratado	','200g',15.00	);
insert into produto (codigo, nomeproduto, unidade, preco)  values ( null,'Cogumelo Shimeji Branco Desidratado	','kg',0.00	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	4927	,'Cogumelo Shimeji desidratado 30g	','30g',11.20	);
insert into produto (codigo, nomeproduto, unidade, preco)  values ( null,'Cogumelo shimeji Desidratado 500g	','500g',0.00	);
insert into produto (codigo, nomeproduto, unidade, preco)  values ( null,'Cogumelo shimeji italia 200g	','Bdj',11.20	);
insert into produto (codigo, nomeproduto, unidade, preco)  values ( null,'Cogumelo shimeji Preto 200g	','200g',11.20	);
insert into produto (codigo, nomeproduto, unidade, preco)  values ( null,'Cogumelo shimeji Rosa 150g	','150g',11.20	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	5462	,'Cogumelo shimeji Salmao 200g	','200g',7.70	);
insert into produto (codigo, nomeproduto, unidade, preco)  values ( null,'Cogumelo Shimofuri 200g	','Bdj',11.20	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	5463	,'Cogumelo Shitake 200G	','Bdj',11.20	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	2475	,'Couve 350g	','350g',2.52	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	5582	,'Couve Mizuma 	','350g',3.53	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	5577	,'Couve-flor  400g	','um',5.60	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	2476	,'Couve-flor KG	','kg',7.42	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	5465	,'Erva cidreira	','70g',2.10	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	2477	,'Ervilha Torta 250g	','250g',4.90	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	2478	,'Espinafre 300g	','300g',3.50	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	5505	,'Feijao Azuki 1kg	','kg',28.42	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	5506	,'Feijao Azuki 500g	','500g',14.70	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	4542	,'Feijao carioquinha 1kg	','kg',18.00	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	5508	,'Feijao de corda 500g	','500g',12.60	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	5509	,'Feijao de corda debulhado 500g	','500g',12.60	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	5510	,'Feijao preto 1kg	','kg',11.90	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	5584	,'Feijao rajadinho 1 kg	','1 kg',13.40	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	5603	,'Feijao verde debulhado 500g	','500g',6.30	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	5511	,'Feijao Verde feixe 500G	','500g',5.36	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	4418	,'Feijao vermelho 	','kg',16.00	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	5590	,'Figo 	','200g',4.20	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	5585	,'Folha de amora 70g	','70g',3.92	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	5673	,'Folha de Crajiru	','70g',3.92	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	5586	,'Folha de graviola 70g	','70g',3.92	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	5680	,'Folha de Louro Desidratada	','5g',3.88	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	5512	,'Folha de Vinagreira 100g	','100g',2.80	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	5513	,'Framboesa	','150g',5.60	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	5514	,'Framboesa congelada	','kg',23.80	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	5415	,'Funcho	','250g',3.36	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	5515	,'Gengibre 200g	','200g',05.04	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	5516	,'Gengibre 500g	','500g',7.00	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	4752	,'Gengibre KG	','kg',14.00	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	5439	,'Goiaba 500g 	','Bdj',5.60	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	5440	,'Goiaba kg	','kg',0.00	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	5517	,'Graviola	','kg',6.37	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	5466	,'Hibisco	','Und',4.20	);
insert into produto (codigo, nomeproduto, unidade, preco)  values ( null,'Hibisco caixa 	','10 kg',0.00	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	2479	,'Hortela 70g	','70g',2.45	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	5481	,'Inga de metro	','um',4.20	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	2480	,'Inhame 1kg	','kg',8.40	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	5263	,'Inhame 500g	','500g',4.90	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	4841	,'Inhame granel kg	','kg',8.40	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	5518	,'Jabuticaba 300g	','und',3.50	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	3041	,'Jaca Desidratada	','un',5.60	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	5519	,'Jaca DURA	','kg',1.61	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	5521	,'Jambo Amarelo	','500g',4.48	);
insert into produto (codigo, nomeproduto, unidade, preco)  values ( null,'Jamelao 200g	','200g',0.00	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	2481	,'Jilo 500g	','500g',3.15	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	5522	,'Jurubeba 100g	','100g',1.26	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	5523	,'Kiwi 	','Bdj',7.28	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	5524	,'Laranja bahia	','kg',4.16	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	5583	,'Laranja cristal 1kg	','kg',5.82	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	5476	,'Laranja Kinkan 200g	','200g',4.20	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	5526	,'Laranja lima embalada	','kg',5.35	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	5528	,'Laranja pera	','kg',5.60	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	5631	,'Legumes Processados	','500g',6.65	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	5529	,'Lichia 300g	','300g',8.40	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	5530	,'Lima da Persia kg	','Kg',5.60	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	5604	,'Lima de bico kg	','Kg',5.60	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	5531	,'Limao China (cravo) 1kg	','kg',4.90	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	4753	,'Limao China (cravo) 500g	','500g',2.45	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	5532	,'Limão China (cravo) granel	','kg',4.20	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	5615	,'Limao Doce 	','500g',3.57	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	5533	,'Limao Galego 500g	','500g',2.80	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	4945	,'Limao Siciliano granel	','kg',6.30	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	1927	,'Limao Tahiti 1kg	','kg',6.90	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	2560	,'Limao Tahiti 500g	','500g',3.80	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	5535	,'Maça importada 500g 	','500g',11.20	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	5534	,'Maça importada KG	','kg',25.20	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	5536	,'Maça Nacional 500g 	','500g',11.20	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	5537	,'Maça Nacional KG	','kg',12.60	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	5538	,'Mamao comum kg	','kg',3.85	);
insert into produto (codigo, nomeproduto, unidade, preco)  values ( null,'Mamao Formosa	','kg',5.39	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	5539	,'Mamao papaya kg	','KG',4.90	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	2482	,'Mandioca c/ Casca kg	','kg',4.20	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	5407	,'Mandioca descascada 500G	','500G',4.90	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	5408	,'Mandioca descascada 750G	','750g',7.00	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	5406	,'Mandioca descascada kg	','kg',8.00	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	5542	,'Manga a granel kg	','kg',9.10	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	5447	,'Manga comum 1 kg	','pct',4.20	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	5541	,'Manga Espada	','kg',4.20	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	5448	,'Manga Palmer	','kg',3.50	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	5543	,'Manga Rosa 	','kg',4.20	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	5544	,'Manga tommy 	','kg',9.10	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	2483	,'Manjericao 70g	','70g',2.38	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	5645	,'Maracujá azedo	','500g',5.60	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	5546	,'Maracuja doce	','kg',9.52	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	5422	,'Maracuja Melao	','kg',7.00	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	5545	,'Maracuja Perola	','kg',5.32	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	5467	,'Mastruz	','mç',2.10	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	2484	,'Maxixe 500g	','500g',2.80	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	5548	,'Melancia	','kg',4.20	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	5558	,'Melancia MINI KG	','kg',5.32	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	5549	,'Melao Amarelo 	','kg',7.00	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	1817	,'Melão Croa	','kg',6.36	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	5416	,'Menta 70g 	','70g',2.41	);
insert into produto (codigo, nomeproduto, unidade, preco)  values ( null,'Menta kg 	','kg',0.00	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	5442	,'Mexerica   1kg	','kg',3.15	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	4865	,'Mexerica  granel	','kg',3.15	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	5557	,'Mexerica Dekopon kg	','kg',3.64	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	2485	,'Milho Verde 1kg	','kg',7.00	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	4599	,'Milho Verde 500g	','500g',2.80	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	5559	,'Mirtilo 125g	','125g',14.00	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	5560	,'Mirtilo bdj	','bdj',6.72	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	5062	,'Morango 250g	','250g',6.50	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	5171	,'Morango Congelado 	','1kg',0.00	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	2486	,'Mostarda	','mç',2.80	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	5398	,'Nabiça	','mç',2.94	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	2487	,'Nabo 500g	','500g',2.94	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	2487	,'Nabo Roxo 	','500g',2.94	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	5561	,'Nectarina	','Bdj',7.00	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	5468	,'Nira	','150g',2.80	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	5624	,'Ora Pro Nobis 100g	','100g',4.20	);
insert into produto (codigo, nomeproduto, unidade, preco)  values ( null,'Ora Pro Nobis 70g	','70g',4.20	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	5425	,'Oregano 70g	','70g',2.45	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	5580	,'Ovo caipira duzia	','dz',11.90	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	5477	,'Ovo Orgânico Caipira Ômega 3 	','dez',16.07	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	5480	,'Ovo Orgânico Caipira Pequeno	','dz',15.43	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	5478	,'Ovo Orgânico Caipira Selenio	','dez',16.07	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	5479	,'Ovo Organico Caipira Vermelho 	','18 und',21.64	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	2872	,'Ovo organico duzia TF	','dz',9.20	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	5469	,'Peixinho 70g	','70g',2.80	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	5435	,'Pepino Caipira 500g	','500g',4.50	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	1615	,'Pepino caipira kg granel	','kg',8.40	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	5562	,'Pepino Holandes 300g	','300g',4.20	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	5470	,'Pepino Holandes 500g	','500g',4.20	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	5563	,'Pepino Japones (granel)	','kg',6.30	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	2488	,'Pepino Japones 500g	','500g',5.00	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	5443	,'Pepino preto 500g	','500g',3.29	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	894	,'Pera importada 	','kg',20.50	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	2971	,'Pera importada 500g 	','500g',11.20	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	4555	,'Pessego	','Bdj',9.80	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	4560	,'Pessego a granel	','kg',0.00	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	5564	,'Pimenta Biquinho Amarela	','100g',2.38	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	5565	,'Pimenta Biquinho Vermelho	','100g',2.38	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	5566	,'Pimenta Bode	','100g',2.38	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	5567	,'Pimenta Caiena	','pct',2.38	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	5568	,'Pimenta de Cheiro	','70g',2.38	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	5569	,'Pimenta Dedo de Moça	','100g',2.38	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	5444	,'Pimenta Malagueta	','35g',2.45	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	5570	,'Pimenta rosa	','20g',5.60	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	5572	,'Pimenta Tabasco	','100g',2.45	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	5574	,'Pimentao Amarelo (granel)	','kg',15.40	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	5734	,'Pimentão Colorido Roxo	','300g',5.60	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	5800	,'Pimentão Colorido 	','300g',6.30	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	4751	,'Pimentao mini colorido	','200g',5.60	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	2489	,'Pimentao Verde 300g	','300g',4.20	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	5471	,'Pimentao verde a granel	','kg',12.60	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	5575	,'Pimentão colorido 	','KG',21.00	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	3488	,'Pimentas 75g	','75g',2.45	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	5573	,'Pimetao amarelo	','300g',5.84	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	5550	,'Pinha	','KG',8.40	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	5605	,'Pitanga 150g	','150g',3.92	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	5419	,'Pitaya (granel)	','kg',12.60	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	5420	,'Poejo	','70g',2.38	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	4948	,'Ponkan Granel	','kg',5.60	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	5551	,'Quiabo (granel)	','kg',9.80	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	2490	,'Quiabo 300g	','300G',4.20	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	5606	,'Rabanete (granel)	','kg',5.85	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	5396	,'Rabanete c/ folha	','600g',2.94	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	2491	,'Rabanete s/ Folha 450g	','450g',2.94	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	5426	,'Radichio	','un',2.80	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	5762	,'Repolho Roxo	','un ',4.20	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	4787	,'Repolho Roxo kg	','kg',4.20	);
insert into produto (codigo, nomeproduto, unidade, preco)  values ( null,'Repolho Roxo restaurante	','kg',3.92	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	2492	,'Repolho Verde KG 	','kg',4.20	);
insert into produto (codigo, nomeproduto, unidade, preco)  values ( null,'Repolho Verde Restaurante*	','kg',3.92	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	5660	,'Repolho Verde UM	','un ',4.20	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	2493	,'Rucula (250g)	','250g',2.52	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	2494	,'Salsa	','mç',2.10	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	2494	,'Salsa Crespa	','und',2.10	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	5472	,'Salsao 350g	','Und',4.90	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	5473	,'Sálvia	','70g',2.80	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	5432	,'Seleta de beterraba/chuchu	','500g',4.90	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	5432	,'Seleta de legumes chu/bet/cen	','500g',4.90	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	5432	,'Seleta de Legumes abob/ chu	','500g',4.90	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	5432	,'Seleta de legumes chuchu/cenoura	','500g',4.90	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	3043	,'Semente de Coentro 20g	','20g',7.00	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	2495	,'Taioba 300g	','300g',2.80	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	5552	,'Tamarindo 300g	','300g',5.35	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	5421	,'Thingensai	','mç',3.36	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	5553	,'Tomate Cereja (granel)	','kg',5.60	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	2496	,'Tomate Cereja 500g	','500g',4.90	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	5607	,'Tomate Grape  (granel)	','kg',12.60	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	2499	,'Tomate Grape 300g	','300g',5.60	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	5399	,'Tomate Grape Amarelo 300g	','300g',5.32	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	5554	,'Tomate Holandes 500g	','500g',3.33	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	5555	,'Tomate Holandes kg	','kg',6.65	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	1616	,'Tomate Italiano (granel) 	','kg',6.00	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	3067	,'Tomate Italiano 1kg	','kg',8.40	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	3601	,'Tomate Italiano 500g	','500g',5.60	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	5609	,'Tomate Mini Cerejao 300g	','300g',4.90	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	4741	,'Tomate Mini Italiano 500g	','500g',5.95	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	5612	,'Tomate mini italiano granel	','kg',11.90	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	5610	,'Tomate mini redondo	','500g',4.90	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	5613	,'Tomate Salada (M) 1 kg especial	','kg',5.88	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	5402	,'Tomate salada (MESA) (granel) 	','kg',7.00	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	2497	,'Tomate salada (MESA) 500g	','500g',4.20	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	2498	,'Tomate salada (MESA)1kg	','kg',7.70	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	5474	,'Tomilho 70g	','70 g',3.33	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	4666	,'Urucum	','20g',4.00	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	5805	,'Urucum em pó 	','50g',5.18	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	1017	,'Uva bdj	','Bdj',7.70	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	5556	,'Uva Isabel	','Bdj',7.70	);
insert into produto (codigo, nomeproduto, unidade, preco)  values ( null,'Uva Niagara	','Bdj',0.00	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	5611	,'Vagem Comum Restaurante*	','kg',9.80	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	2500	,'Vagem Macarrao (comum) 300g	','300g',4.20	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	5608	,'Vagem Paulista (granel)	','kg',9.80	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	2501	,'Vagem Paulista 300g	','300g',4.90	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	5023	,'Major Gomes	','100g',4.20	);
insert into produto (codigo, nomeproduto, unidade, preco)  values (	5249	,'Couve picada 	','150g',4.20	);